### ISSUE TITLE
Where and how are the php files being uploaded to the esp8266.

### ISSUE THREAD

**Issue by sebinbc** [hananabilabd/Reading-Sensor-Data-saving-it-to-ESP8266-Webserver-using-Xampp-Python-Visualization#1]
Hey, great work !
I had a small doubt, how are you uploading the .php file over to the esp8266.
because there is one line in your code which says:
client.print("GET /write_data.php?")
Obviously this will try to connect to the write_data.php how can it do that if it has not yet been uploaded to the esp8266?
Thanks.﻿

**Comment by hananabilabd** [comment]
Hello 
Sorry for late reply 
But you should put the . php files to your directory where Xampp is installed 
should look like "C:\xampp\htdocs" (something like that ) 
Regards
